name: Test Elastic Container Setup on Windows

on:
  push:
    branches:
      - main 

jobs:
  setup-and-test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JQ (if needed)
        run: choco install jq
        shell: pwsh
      
      - name: Prepare and Run Install (Docker Compose)
        run: |
          bash ./elastic-container.sh start
        shell: bash
          
      - name: Validate Setup
        run: |
          docker ps
        shell: pwsh

      - name: Obtain Fleet Enrollment Token
        run: |
          bash ./enrollment_token.sh
        shell: bash
